# Generated by Django 5.2.7 on 2025-10-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="github",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="linkedin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
