# Generated by Django 5.2.7 on 2025-10-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="link",
        ),
        migrations.AddField(
            model_name="project",
            name="githubUrl",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="liveUrl",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
