# Generated by Django 5.2.7 on 2025-10-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_project_category_alter_personalinfo_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(to="api.skill"),
        ),
    ]
