# Generated by Django 5.2.7 on 2025-10-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_personalinfo_address_alter_personalinfo_bio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalinfo",
            old_name="proffessional_title",
            new_name="proffessionalTitle",
        ),
    ]
