# Generated by Django 5.2.7 on 2025-10-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_project_technologies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="api.skill"),
        ),
    ]
