# Generated by Django 5.2.7 on 2025-10-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_proffessional_title_personalinfo_proffessionaltitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectachievement",
            name="achievement",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="projectchallenge",
            name="challenge",
            field=models.CharField(max_length=500),
        ),
    ]
