# Generated by Django 5.2.7 on 2025-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_projectachievement_achievement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectachievement",
            name="achievement",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projectchallenge",
            name="challenge",
            field=models.TextField(),
        ),
    ]
