# Generated by Django 5.2.7 on 2025-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_project_technologies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
