# Generated by Django 5.2.7 on 2025-10-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_skill_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalinfo",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterModelOptions(
            name="projectachievement",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterModelOptions(
            name="projectchallenge",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterModelOptions(
            name="projectimage",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="projectachievement",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="projectachievement",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="projectchallenge",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="projectchallenge",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
