# Generated by Django 5.2.7 on 2025-11-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_personalinfo_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField()),
            ],
            options={
                "ordering": ["-createdAt"],
                "abstract": False,
            },
        ),
    ]
