# Generated by Django 5.1 on 2025-11-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="projectimage",
            options={"ordering": ["createdAt"]},
        ),
    ]
