# Generated by Django 5.1 on 2026-01-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_project_options_alter_projectimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="showInPortfolio",
            field=models.BooleanField(default=True),
        ),
    ]
