# Generated by Django 5.1 on 2026-01-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_project_showinportfolio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-startDate"]},
        ),
    ]
