# Generated by Django 5.1 on 2026-01-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_project_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-createdAt"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="current_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.experience",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.experience",
            ),
        ),
    ]
