# Generated by Django 5.1 on 2026-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_experience_personalinfo_current_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="employment_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
